# Generated by Django 4.2.3 on 2024-03-10 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa_firmy", models.CharField(blank=True, max_length=225)),
                ("adres", models.CharField(blank=True, max_length=255)),
                ("kod_pocztowy", models.CharField(blank=True, max_length=20)),
                ("miasto", models.CharField(blank=True, max_length=120)),
                ("NIP", models.CharField(blank=True, max_length=20)),
                ("telefon", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
