# Generated by Django 4.2.3 on 2024-03-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_orderitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="NIP",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
