# Generated by Django 4.2.3 on 2024-02-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tax",
            field=models.IntegerField(
                choices=[(0, "0%"), (5, "5%"), (8, "8%"), (23, "23%")], default=23
            ),
        ),
    ]
