# Generated by Django 4.2.3 on 2024-02-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_tax"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="colour",
            field=models.CharField(
                blank=True,
                choices=[
                    ("black", "Czarny"),
                    ("blue", "Niebieski"),
                    ("green", "Zielony"),
                    ("grey", "Szary"),
                    ("red", "Czerwony"),
                    ("transparent", "Bezbarwny"),
                    ("white", "Biały"),
                    ("yellow", "Żółty"),
                ],
                max_length=24,
                null=True,
            ),
        ),
    ]
